name: example_custom_theme
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  blur: ^4.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image10.png
  fonts:
    - family: Commission
      fonts:
        - asset: assets/fonts/commission-ultracondensed.otf
    - family: CommissionOutlined
      fonts:
        - asset: assets/fonts/commission-ultracondensedoutlined.otf
    - family: PixelOperator
      fonts:
        - asset: assets/fonts/PixelOperator.ttf
    - family: TASAOrbiterDeck
      fonts:
        - asset: assets/fonts/TASAOrbiterDeck-Regular-BF64891cba23854.otf
